config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "devise/registrations", sessions: "devise/sessions" }
  resources :carritos
  resources :productos
  resources :users

  post "/carritos/:id/comprar", to: "carritos#comprar", as: "comprar"
  post "/carritos/:id/add_product", to: "carritos#add_product", as: "add_product"
  post "/carritos/:id/sumar_cantidad", to: "carritos#sumar_cantidad", as: "sumar_cantidad"
  get "/carritos/:id/buscar", to: "carritos#buscar", as: "buscar"
  post "/carritos/:id/remove_product", to: "carritos#remove_product", as: "remove_product"
  root 'productos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_one :carrito
  has_many :reportes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
      @carrito =Carrito.new(cantidad_productos: params[:user][:cantidad_productos].to_i)
  
    @user = @carrito.build_user(user_params)
  
    
  
    respond_to do |format|
      if @carrito.save
        format.html { redirect_to root_path, notice: 'Usuario creado de forma exitosa.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if !@user.reportes.empty?
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'Usuario eliminado de forma exitosa.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'El usuario ha realizado compras y no puede ser eliminado.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:documento, :NIT, :telefono, :nombre, :direccion, :celular, :ciudad, :password, :profesion, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
  <div class="panel-groupb">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Registro</h4></div>
      <div class="panel-body">
        <div class="labela">
            <div id="select-box" class="under-space"><%= form.select :roles, options_for_select([["Persona Natural", "natural"], ["Persona Juridica", "juridica"]]) %></div>
            
    <%= form.label :documento %>
  <div class="field">
    <%= form.text_field :documento, id: :user_documento, required: true %>
  </div>
  <div id="nit">
      <%= form.label :NIT %>
      <div class="field">
       <%= form.text_field :NIT, id: :user_NIT %>
     </div>
  </div>
    

    <%= form.label :telefono %>
   <div class="text_field">
    <%= form.text_field :telefono, id: :user_telefono, required: true %>
  </div>

    <%= form.label :nombre %>
   <div class="field">
    <%= form.text_field :nombre, id: :user_nombre, required: true %>
  </div>
  
    <%= form.label :direccion %>
   <div class="field">
    <%= form.text_field :direccion, id: :user_direccion, required: true %>
  </div>

  
    <%= form.label :celular %>
    <div class="field">
      <%= form.text_field :celular, id: :user_celular %>
  </div>

  
    <%= form.label :ciudad %>
    <div class="field">
      <%= form.text_field :ciudad, id: :user_ciudad, required: true %>
  </div>

  
    <%= form.label :password %>
   <div class="field">
    <%= form.text_field :password, id: :user_password %>
  </div>

 
    <%= form.label :profesion %>
    <div class="field">
     <%= form.text_field :profesion, id: :user_profesion, required: true %>
  </div>

  
    <%= form.label :email %>
   <div class="field">
    <%= form.text_field :email, id: :user_correo, required: true %>
  </div><br>


  <div class="actions text-center">
    <%= form.submit "Crear Usuario", class:"btn btn-primary" %>
  </div>
<% end %>
</div></div>
</div>
</div>
</div>

app/views/users/edit.html.erb
<div class="jumbotron text-center">
      <h1>Editando usuario</h1> 
</div>
<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
 <div class="jumbotron text-center">
      <h1>Usuarios</h1> 
</div>

<div class="containerb">
<table class="table table-bordered">
  <thead>
    <tr>
      <th><div class="labele">Documento</div></th>
      <th><div class="labele">Nit</div></th>
      <th><div class="labele">Telefono</div></th>
      <th><div class="labele">Nombre</div></th>
      <th><div class="labele">Direccion</div></th>
      <th><div class="labele">Celular</div></th>
      <th><div class="labele">Ciudad</div></th>
      <th><div class="labele">Password</div></th>
      <th><div class="labele">Profesion</div></th>
      <th><div class="labele">Correo</div></th>
      <th colspan="3"></th>
    </tr>
  </thead>
 

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><div class="labelf"><%= user.documento %></div></td>
        <td><div class="labelf"><%= user.NIT %></div></td>
        <td><div class="labelf"><%= user.telefono %></div></td>
        <td><div class="labelf"><%= user.nombre %></div></td>
        <td><div class="labelf"><%= user.direccion %></div></td>
        <td><div class="labelf"><%= user.celular %></div></td>
        <td><div class="labelf"><%= user.ciudad %></div></td>
        <td><div class="labelf"><%= user.password %></div></td>
        <td><div class="labelf"><%= user.profesion %></div></td>
        <td><div class="labelf"><%= user.correo %></div></td>
        <td><div class="labelf"><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr></div>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New User', new_user_path %>
<br><br><br>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="containerb">
    <table class="table table-bordered">
       <thead>
         <tr>
          <th><div class="labele">Documento:</div></th>
           <th><div class="labele">Nit:</div></th>
           <th><div class="labele">Telefono:</div></th>
           <th><div class="labele">Nombre:</div></th>
           <th><div class="labele">Direccion:</div></th>
           <th><div class="labele">Celular:</div></th>
           <th><div class="labele">Ciudad:</div></th>
           <th><div class="labele">Password:</div></th>
           <th><div class="labele">Profesion:</div></th>
           <th><div class="labele">Correo:</div></th>
            </tr>
    </thead>
    <tbody>
      <tr>
         <td><div class="labelf"><%= @user.documento %></div></td>
           <td><div class="labelf">
             <% if @user.NIT.empty?%>
                No presenta
              <% else %>  
              <%= @user.NIT %>
              <% end %>
            </div></td>
             <td><div class="labelf"><%= @user.telefono %></div></td>
             <td><div class="labelf"><%= @user.nombre %></div></td>
             <td><div class="labelf"><%= @user.direccion %></div></td>
             <td><div class="labelf"><%= @user.celular %></div></td>
             <td><div class="labelf"><%= @user.ciudad %></div></td>
             <td><div class="labelf"><%= @user.password %></div></td>
             <td> <div class="labelf"><%= @user.profesion %></div></td>
             <td><div class="labelf"><%= @user.email %></div></td>
             </tr>
    </tbody>
  </table>
  </div>



<%= link_to 'Editar', edit_user_path(@user), class:"btn btn-primary" %>
<%= link_to 'Volver', productos_path, class:"btn btn-primary" %>