config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "devise/registrations", sessions: "devise/sessions" }
  resources :carritos
  resources :productos
  resources :users

  post "/carritos/:id/comprar", to: "carritos#comprar", as: "comprar"
  post "/carritos/:id/add_product", to: "carritos#add_product", as: "add_product"
  post "/carritos/:id/sumar_cantidad", to: "carritos#sumar_cantidad", as: "sumar_cantidad"
  get "/carritos/:id/buscar", to: "carritos#buscar", as: "buscar"
  post "/carritos/:id/remove_product", to: "carritos#remove_product", as: "remove_product"
  root 'productos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carrito.rb
class Carrito < ApplicationRecord
	belongs_to :user 
    has_many :carrito_productos
    has_many :productos, through: :carrito_productos

    def restar_productos
        reporte = Reporte.new
        self.carrito_productos.each do |carrito_producto|
            producto = carrito_producto.producto
            inventario = producto.inventario
            reporte.productos << producto
            producto.cantidad = producto.cantidad - 1
            inventario.cantidad = producto.cantidad
            producto.save
            inventario.save
        end
        reporte.user = self.user
        reporte.save
    end

    def sumar_productos
        suma_productos = 0
        self.carrito_productos.each do |carrito_producto|
            producto = carrito_producto.producto
            suma_productos = producto.precio + suma_productos
        end
        suma_productos
    end
    
end

app/controllers/carritos_controller.rb
class CarritosController < ApplicationController
  before_action :set_carrito, only: [:show, :edit, :update, :destroy, :add_product, :comprar, :remove_product, :buscar, :sumar_cantidad]

  # GET /carritos
  # GET /carritos.json
  def index
    @carrito = current_user.carrito
    @carritos = @carrito.carrito_productos
  end
  def buscar 
    @product = @carrito.carrito_productos.find(params[:producto_id])
  end
  # GET /carritos/1
  # GET /carritos/1.json
  def show
  end

  def comprar
    @carrito.restar_productos
    @suma_total = @carrito.sumar_productos
    UserMailer.send_confirmation(current_user.email, @carrito.carrito_productos, @suma_total ).deliver
    @carrito.carrito_productos.destroy_all
    flash[:success] = "Compra Exitosa"
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Compra realizada exitosamente' }
    end
  end

  def sumar_cantidad
     @carrito_producto.cantidad_productos  = @carrito_producto.cantidad_productos+1
    @carrito_producto.save
  end
  # GET /carritos/new
  def new
    @carrito = Carrito.new
  end

  def add_product
    @producto = Producto.find(params[:producto_id])
    @carrito_producto = @carrito.carrito_productos.new
    @carrito_producto.producto = @producto
    @carrito_producto.cantidad_productos = 0
    @carrito_producto.cantidad_productos = @carrito_producto.cantidad_productos+1
    @carrito_producto.save
    @carrito.save
    respond_to do |format|
      format.html { redirect_to productos_path, notice: 'Producto agregado al carrito de compras' }
    end
  end
  def remove_product
    @carrito.carrito_productos.find_by_producto_id(params[:producto_id]).destroy
  end

  # GET /carritos/1/edit
  def edit
  end

  # POST /carritos
  # POST /carritos.json
  def create
    
    @carrito = Carrito.new(carrito_params)
    
    respond_to do |format|
      if @carrito.save
        format.html { redirect_to @carrito, notice: 'Carrito was successfully created.' }
        format.json { render :show, status: :created, location: @carrito }
      else
        format.html { render :new }
        format.json { render json: @carrito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carritos/1
  # PATCH/PUT /carritos/1.json
  def update
    respond_to do |format|
      if @carrito_producto.update(params[:cantidad_productos])
        format.html { redirect_to @carrito_producto, notice: 'Carrito was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrito_producto }
      else
        format.html { render :edit }
        format.json { render json: @carrito_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carritos/1
  # DELETE /carritos/1.json
  def destroy
    @carrito.destroy
    respond_to do |format|
      format.html { redirect_to carritos_url, notice: 'Carrito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrito
      @carrito = Carrito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrito_params
      params.require(:carrito).permit(:cantidad_productos)
    end
end

app/helpers/carritos_helper.rb
module CarritosHelper
end

app/views/carritos/_form.html.erb
<%= form_with(model: carrito, local: true) do |form| %>
  <% if carrito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carrito.errors.count, "error") %> prohibited this carrito from being saved:</h2>

      <ul>
      <% carrito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cantidad_productos %>
    <%= form.number_field :cantidad_productos, id: :carrito_cantidad_productos %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carritos/edit.html.erb
<h1>Editing Carrito</h1>

<%= render 'form', carrito: @carrito %>

<%= link_to 'Show', @carrito %> |
<%= link_to 'Back', carritos_path %>

app/views/carritos/index.html.erb
<p id="notice"><%= notice %></p>
    <% contador_computador = 0 %>
    <% contador_portatil = 0 %>
    <% contador_tablet = 0 %>
    <% precio_computador= 0  %>
    <% precio_portatil= 0  %>
    <% precio_tablet = 0 %>
<div class="jumbotron text-center">
      <h1>Carrito</h1> 
</div>

<div class="containerb">
    <table class="table table-bordered" style="width:70%; margin-left: auto; margin-right:auto;">
       <thead>
         <tr>
           <th><div class="labele">Acciones</div></th>
           <th><div class="labele">Producto</div></th>
           <th><div class="labele">Cantidad productos</div></th>
           <th><div class="labele">Precio</div></th>
           <th><div class="labele">Total</div></th>
    </tr>
  </thead>

  <tbody>
    <% @carritos.each do |carrito| %>
      <% if carrito.producto.tipo == "computador" %>
        <% precio_computador = carrito.producto.precio %>
        <% if contador_computador > 0 %>
          <% contador_computador = contador_computador + 1 %>
        <% else %>
          <% contador_computador = contador_computador + 1 %>
          <tr>   
            <td><div class="labelf"><%= link_to 'Ver Detalles', carrito.producto %></div></td>
            <td><div class="labelf"><%= carrito.producto.nombre %></div></td>
            <td id="contador_computador"><div class="labelf"><%= contador_computador %></div></td>
            <td><%= carrito.producto.precio %></td>
            <td id="total_computador"></td>   
          </tr>
        <% end %>
      <% end %>
      <% if carrito.producto.tipo == "portatil" %>
      <% precio_portatil = carrito.producto.precio %>
        <% if contador_portatil > 0 %>
          <% contador_portatil = contador_portatil + 1 %>
        <% else %>
          <% contador_portatil = contador_portatil + 1 %>
          <tr>
            <td><div class="labelf"><%= link_to 'Ver Detalles', carrito.producto %></div> </td>
            <td><div class="labelf"><%= carrito.producto.nombre %></td></div>
            <td id="contador_portatil"><div class="labelf"><%= contador_portatil %></div> </td>
            <td><%= carrito.producto.precio %></td>
            <td id="total_portatil"></td>
          </tr>
        <% end %>
      <% end %>
      <% if carrito.producto.tipo == "tablet" %>
        <% precio_tablet = carrito.producto.precio %>
        <% if contador_tablet > 0 %>
          <% contador_tablet = contador_tablet + 1 %>
        <% else %>
          <% contador_tablet = contador_tablet + 1 %>
          <tr>
            <td><div class="labelf"><%= link_to 'Ver Detalles', carrito.producto %></div></td>
            <td><div class="labelf"><%= carrito.producto.nombre %></div> <td>
              <td id="contador_tablet"> <div class="labelf"><%= contador_tablet %></div> </td>
              <td><%= carrito.producto.precio %></td>
            <td id="total_tablet"></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
   </tbody></table></div>
   <% total_computador = precio_computador * contador_computador %>
   <% total_portatil = precio_portatil * contador_portatil %>
   <% total_tablet = precio_tablet * contador_tablet %>
   <% total_absoluto = total_computador + total_portatil + total_tablet %>

<br>

<div class="labelc"><%= link_to 'Comprar', comprar_path(@carrito),id:"absolute_total", class:"btn btn-primary", method: :post %></div>

<script>
  $('#contador_computador').html("<%= contador_computador %>");
  $('#total_computador').html("<%= total_computador %>");
  $('#contador_portatil').html("<%= contador_portatil %>");
  $('#total_portatil').html("<%= total_portatil %>");
  $('#contador_tablet').html("<%= contador_tablet %>");
  $('#total_tablet').html("<%= total_tablet %>");
  $('#absolute_total').html("¿ Comprar por <%= total_absoluto %> ?");

</script>

app/views/carritos/new.html.erb
<h1>New Carrito</h1>

<%= render 'form', carrito: @carrito %>

<%= link_to 'Back', carritos_path %>

app/views/carritos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad productos:</strong>
  <%= @carrito_producto.cantidad_productos  %>
</p>

<%= link_to 'Edit', edit_carrito_path(@carrito) %> |
<%= link_to 'Back', carritos_path %>