config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "devise/registrations", sessions: "devise/sessions" }
  resources :carritos
  resources :productos
  resources :users

  post "/carritos/:id/comprar", to: "carritos#comprar", as: "comprar"
  post "/carritos/:id/add_product", to: "carritos#add_product", as: "add_product"
  post "/carritos/:id/sumar_cantidad", to: "carritos#sumar_cantidad", as: "sumar_cantidad"
  get "/carritos/:id/buscar", to: "carritos#buscar", as: "buscar"
  post "/carritos/:id/remove_product", to: "carritos#remove_product", as: "remove_product"
  root 'productos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/producto.rb
class Producto < ActiveRecord::Base
    after_validation :create_inventario
    belongs_to :inventario, optional: true
    has_many :carrito_productos
    has_many :carritos, through: :carrito_productos
    has_and_belongs_to_many :reportes

    has_attached_file :foto, styles: { medium: "300x300", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/

    def self.search(search)
      where("nombre LIKE ? OR descripcion LIKE ? OR tipo LIKE ? OR material LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
    end

    def create_inventario
      inventario = Inventario.new(cantidad: self.cantidad, precio: self.precio* self.cantidad)
      inventario.save
      self.inventario = inventario
    end
     def sumar_cantidad
    cantidad = Producto.carrito_productos.cantidad_productos+1
    Producto.carrito_productos.cantidad_productos.save
    self.carrito_productos.cantidad_productos = cantidad
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
@producto = Producto.all
  if params[:search]
    @productos = Producto.search(params[:search]).order("created_at DESC")
  else
    @productos = Producto.all.order("created_at DESC")
  end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    
    @producto = Producto.new


  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
     @inventario =Inventario.new(cantidad: params[:producto][:cantidad].to_i,precio: params[:producto][:cantidad]*params[:producto][:precio].to_i)
  
    @producto = @inventario.build_producto(producto_params)
  
  

    respond_to do |format|
      if @inventario.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :tipo, :material, :dimenciones, :color, :peso, :precio, :cantidad, :foto)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_with model: producto, html: { multipart: true } do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
  <div class="panel-groupc">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Productos</h4></div>
      <div class="panel-body">
        <div class="labela">

  
    <%= form.label :foto %>
    <div class="field">
    <%= form.file_field :foto, id: :producto_foto %>
  </div>
  
    <%= form.label :nombre %>
    <div class="field">
    <%= form.text_field :nombre, id: :producto_nombre %>
  </div>
   
  
    <%= form.label :descripcion %>
    <div class="field">
    <%= form.text_field :descripcion, id: :producto_descripcion %>
  </div>

  
    <%= form.label :tipo %>
    <div class="field">
    <%= form.text_field :tipo, id: :producto_tipo %>
  </div>

  
    <%= form.label :material %>
    <div class="field">
    <%= form.text_field :material, id: :producto_material %>
  </div>

  
    
      <%= form.label :precio %>
      <div class="field">
      <%= form.text_field :precio, id: :producto_precio %>
    </div>    
  </div>

  
    <%= form.label :dimenciones %>
    <div class="field">
    <%= form.text_field :dimenciones, id: :producto_dimenciones %>
  </div>

  
    <%= form.label :color %>
    <div class="field">
    <%= form.text_field :color, id: :producto_color %>
  </div>

  
    <%= form.label :peso %>
    <div class="field">
    <%= form.number_field :peso, id: :producto_peso %>
  </div>
  
    <%= form.label :cantidad %>
    <div class="field">
    <%= form.number_field :cantidad, id: :producto_cantidad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div></div></div></div></div>
 
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form', producto: @producto %>
<%= render template: "users/show"%>
<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="\assets\ot.png" alt="ot"  width="1000" height="300">   
        </div>
        <div class="item">
            <img src="\assets\acer.png" alt="Acer" width="1000" height="300">
        </div>
        <div class="item">
            <img src="\assets\toshiba.png" alt="Toshiba" width="1000" height="300">    
        </div>
        <div class="item">
            <img src="\assets\asus.png" alt="Asus" wsidth="1000" height="300">    
        </div>
        <div class="item">
            <img src="\assets\dell.png" alt="Dell" width="1000" height="300">    
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div><br>

<div class="jumbotron text-center">
    <h1>Productos</h1> 
    
    <%= form_tag(productos_path, :method => "get", id: "search-form", class:"form-inline") do %>
        <div class="input-group">
            <%= text_field_tag :search, params[:search], placeholder: "Ingrese nombre pc", class:"form-control", size:"50" %>
            <div class="input-group-btn">
                <%= submit_tag "Buscar", :name => nil, class:"btn btn-danger" %>
            </div>
        </div>
    <% end %>
</div>

<br><br>
<div id="myPage" class="containera">
    <div class="panel-groupa">
        <div class="panel panel-default">
            <div class="panel-heading"style="font-weight:bold;">
                Productos disponibles
            </div>
            <div class="panel-bodya" style="padding-left: 20px;padding-right: 20px;">
                <div class="row">
                    <% @productos.each do |producto| %>
                        <div class="col-xs-12 col-lg-3" style="margin-top:2em; margin-bottom: 2em;">
                            <%= link_to producto do %>
                                <div style="border:thin solid black;">
                                    <%= image_tag producto.foto.url(:medium) %>
                                    <div class="text-container">
                                        <h6><%= producto.nombre %></h6>
                                        <p><%= producto.descripcion %></p>
                                        <h6 class="cash">$<b><%= producto.precio %></b></h6>
                                        <% if user_signed_in? %>
                                             <%= link_to buscar_path(id: current_user.carrito.id , producto_id:producto.id), method: :get, remote: true do %>
                                             <% end %>
                                             <% if producto==@product %>
                                                   <%producto.sumar_cantidad( producto_id:producto.id)%> 
                                             <% else %>
                                                    <%=link_to add_product_path(id: current_user.carrito.id , producto_id:producto.id), method: :post, remote: true do %>
                                                        <span class="glyphicon glyphicon-shopping-cart"></span>
                                                        Agregar al carrito
                                                    <% end %>
                                            <% end %>
                                                
                                    <% end %>
                                              
                                           
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/productos/new.html.erb
<br><div class="texto"><h1>Producto nuevo</h1></div>

<%= render 'form', producto: @producto %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %>
  <div class="row">
    <div class="col-lg-12">
      <div id="producto-contenedor-descripcion" class="text-center" style="background: white;">
          <h2><%= @producto.nombre %></h2>
          <%= image_tag @producto.foto.url(:medium) %>
          <table class="table-bordered" style="margin-left: auto;margin-right: auto;width: 40%; margin-top:2em;">
            <tr>
              <td class="bold">Descripcion</td>
              <td> <%= @producto.descripcion %></td>
            </tr>
            <tr>
              <td class="bold">Tipo</td>
              <td> <%= @producto.tipo%></td>
            </tr>
            <tr>
              <td class="bold">Material</td>
              <td> <%= @producto.material %></td>
            </tr>
            <tr>
              <td class="bold">Dimensiones</td>
              <td> <%= @producto.dimenciones %></td>
            </tr>
            <tr>
              <td class="bold">Color</td>
              <td> <%= @producto.color %></td>
            </tr>
            <tr>
              <td class="bold">Peso</td>
              <td> <%= @producto.peso %></td>
            </tr>
            <tr>
              <td class="bold">Precio</td>
              <td> <%= @producto.precio %></td>
            </tr>
          </table>
          <div class=" row text-center" style="margin-top:1em;">
              <% if user_signed_in? %>
                <%= link_to add_product_path(id: current_user.carrito.id , producto_id: @producto.id), method: :post, class:"btn btn-success" do %>
                  <span class="glyphicon glyphicon-shopping-cart"></span>
                  Agregar al carrito
                <% end %>
              <% end %>
              <%= link_to 'Volver', productos_path, class:"btn btn-primary" %>
          </div>
      </div>
    </div>
  </div>
  